dbfilename redis_queue.rdb
dir /home/sharieff/frappe-project/bench/pest/config/pids
pidfile /home/sharieff/frappe-project/bench/pest/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/sharieff/frappe-project/bench/pest/config/redis_queue.acl
